listen = *
ssl = required
ssl_min_protocol = TLSv1.2
ssl_server_cert_file = /etc/letsencrypt/live/mail.sveevee.co.il/fullchain.pem
ssl_server_key_file = /etc/letsencrypt/live/mail.sveevee.co.il/privkey.pem

auth_allow_cleartext = no
auth_mechanisms = plain login
auth_cache_size = 10M

mail_driver = maildir
mail_home = /var/vmail/%{user | domain}/%{user | username}
mail_path = %{home}/Maildir
mail_inbox_path = %{home}/Maildir
mail_uid = vmail
mail_gid = vmail
mail_privileged_group =
first_valid_uid = 5000
last_valid_uid = 5000

passdb passwd-file {
  default_password_scheme = ARGON2ID
  auth_username_format = %{user | lower}
  passwd_file_path = /etc/dovecot/users
}

userdb static {
  fields {
    uid = vmail
    gid = vmail
    home = /var/vmail/%{user | domain}/%{user | username}
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

protocol lmtp {
  auth_username_format = %{user | lower}
  postmaster_address = postmaster@sveevee.co.il
}
