[program:sveevee-reverb]
process_name=%(program_name)s
directory=/var/www/sveevee/backend
command=/usr/bin/php artisan reverb:start --host=127.0.0.1 --port=8080
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/sveevee-reverb.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stopwaitsecs=10
