server {
    listen 80;
    listen [::]:80;
    server_name mail.sveevee.co.il webmail.sveevee.co.il mta-sts.sveevee.co.il autoconfig.sveevee.co.il;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/mail-acme;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

