<?php

// Explicit aliases from sveevee-worker/config/worker.foursquare.json city_names,
// also used by the Overture/Gov profiles; Tel Aviv-Yafo is the mapper default.
// Only targets present in locations.cities are accepted. Never infer new aliases.
$aliases = [
    'Jerusalem' => ['ירושלים'],
    'Tel Aviv' => ['תל אביב - יפו', 'תל אביב', 'תל  אביב', 'תל אביב יפו', 'Tel Aviv-Yafo'],
    'Haifa' => ['חיפה'],
    'Beersheba' => ['באר שבע'],
    'Rishon LeZion' => ['ראשון לציון'],
    'Petah Tikva' => ['פתח תקווה', 'פתח תקוה'],
    'Netanya' => ['נתניה'],
    'Ashdod' => ['אשדוד'],
    'Ashkelon' => ['אשקלון'],
    'Holon' => ['חולון'],
    'Bat Yam' => ['בת ים'],
    'Ramat Gan' => ['רמת גן'],
    'Bnei Brak' => ['בני ברק'],
    'Herzliya' => ['הרצליה'],
    'Ra\'anana' => ['רעננה'],
    'Kfar Saba' => ['כפר סבא'],
    'Modi\'in-Maccabim-Reut' => ['מודיעין-מכבים-רעות', 'מודיעין מכבים רעות'],
    'Rehovot' => ['רחובות'],
    'Lod' => ['לוד'],
    'Ramla' => ['רמלה'],
    'Givatayim' => ['גבעתיים'],
    'Hadera' => ['חדרה'],
    'Nahariya' => ['נהריה'],
    'Acre' => ['עכו'],
    'Tiberias' => ['טבריה'],
    'Safed' => ['צפת'],
    'Eilat' => ['אילת'],
    'Kiryat Ono' => ['קריית אונו'],
    'Givat Shmuel' => ['גבעת שמואל'],
    'Yehud-Monosson' => ['יהוד-מונוסון', 'יהוד'],
    'Or Yehuda' => ['אור יהודה'],
    'Rosh HaAyin' => ['ראש העין'],
    'Hod HaSharon' => ['הוד השרון'],
    'Ness Ziona' => ['נס ציונה'],
    'Kiryat Gat' => ['קריית גת', 'קרית גת'],
    'Kiryat Malakhi' => ['קריית מלאכי'],
    'Dimona' => ['דימונה'],
    'Arad' => ['ערד'],
    'Sderot' => ['שדרות'],
    'Netivot' => ['נתיבות'],
    'Ofakim' => ['אופקים'],
    'Karmiel' => ['כרמיאל'],
    'Afula' => ['עפולה'],
    'Beit Shean' => ['בית שאן'],
    'Nazareth' => ['נצרת'],
    'Nof HaGalil' => ['נוף הגליל'],
    'Beit Shemesh' => ['בית שמש'],
    'Maale Adumim' => ['מעלה אדומים'],
    'Ariel' => ['אריאל'],
    'Alfei Menashe' => ['אלפי מנשה'],
    'Ganei Tikva' => ['גני תקווה'],
    'Tirat Carmel' => ['טירת כרמל'],
    'Ramat Hasharon' => ['רמת השרון'],
    'Yavne' => ['יבנה'],
    'Gedera' => ['גדרה'],
    'Beer Yaakov' => ['באר יעקב'],
    'Migdal HaEmek' => ['מגדל העמק'],
    'Yokneam Illit' => ['יקנעם עילית'],
    'Kiryat Bialik' => ['קריית ביאליק'],
    'Kiryat Motzkin' => ['קריית מוצקין'],
    'Kiryat Yam' => ['קריית ים'],
    'Kiryat Ata' => ['קריית אתא'],
    'Nesher' => ['נשר'],
    'Zikhron Yaakov' => ['זכרון יעקב'],
    'Pardes Hanna-Karkur' => ['פרדס חנה-כרכור'],
    'Kiryat Tivon' => ['קריית טבעון'],
    'Ramat Yishai' => ['רמת ישי'],
    'Kfar Yona' => ['כפר יונה'],
    'Tira' => ['טירה'],
    'Taibe' => ['טייבה'],
    'Umm al-Fahm' => ['אום אל-פחם', 'אום אל פחם', 'אום אלפחם'],
    'Sakhnin' => ['סח\'נין'],
    'Tamra' => ['טמרה'],
    'Shefa-Amr' => ['שפרעם'],
    'Kiryat Shmona' => ['קריית שמונה', 'קרית שמונה'],
    'Rosh Pina' => ['ראש פינה'],
    'Katzrin' => ['קצרין'],
    'Kiryat Arba' => ['קריית ארבע', 'קרית ארבע'],
    'Efrat' => ['אפרת'],
    'Givat ZeEv' => ['גבעת זאב'],
    'Mevaseret Zion' => ['מבשרת ציון'],
    'Shoeva' => ['שואבה'],
    'Shoham' => ['שוהם'],
];

// Official CBS 2024 names plus individually audited observed spellings, not fuzzy matches.
// Only residential localities and existing catalog names are eligible; see docs/import-city-catalog.md.
$reviewed = json_decode(file_get_contents(__DIR__.'/../resources/data/import-city-catalog.json'), true, 512, JSON_THROW_ON_ERROR);
foreach ($reviewed['cities'] as $city) {
    $aliases[$city['name']] = array_values(array_unique([
        ...($aliases[$city['name']] ?? []), ...$city['aliases'],
    ]));
}

return $aliases;
