<?php

return [
    'cities' => [
        [
            'name' => 'Jerusalem',
            'neighborhoods' => [
                'Abu Tor',
                'Arnona',
                'Baka',
                'Bayit Vegan',
                'City Center',
                'Ein Karem',
                'French Hill',
                'German Colony',
                'Gilo',
                'Har Nof',
                'Katamon',
                'Kiryat HaYovel',
                'Kiryat Menachem',
                'Kiryat Moshe',
                'Musrara',
                'Nachlaot',
                'Old City',
                'Pisgat Zeev',
                'Ramot',
                'Ramat Eshkol',
                'Rehavia',
                'Sanhedria',
                'Talpiot',
            ],
        ],
        [
            'name' => 'Tel Aviv',
            'neighborhoods' => [
                'Bavli',
                'Florentin',
                'HaTikva',
                'Jaffa',
                'Kerem HaTeimanim',
                'Kiryat Shalom',
                'Lev HaIr',
                'Neve Tzedek',
                'Old North',
                'Ramat Aviv',
                'Ramat HaHayal',
                'Rothschild',
                'Sarona',
                'Shapira',
                'Yad Eliyahu',
            ],
        ],
        [
            'name' => 'Haifa',
            'neighborhoods' => [
                'Ahuza',
                'Bat Galim',
                'Carmel Center',
                'Downtown',
                'German Colony',
                'Hadar',
                'Kiryat Eliezer',
                'Kiryat Haim',
                'Kiryat Shmuel',
                'Neve David',
                'Neve Shaanan',
                'Ramat Almogi',
                'Romema',
                'Stella Maris',
                'Vardia',
            ],
        ],
        [
            'name' => 'Beersheba',
            'neighborhoods' => [
                'Dalet',
                'Gimel',
                'Hey',
                'Nahal Ashan',
                'Nahal Beka',
                'Neve Zeev',
                'Old City',
                'Ramot',
                'Vav',
                'Yud Alef',
            ],
        ],
        [
            'name' => 'Rishon LeZion',
            'neighborhoods' => [
                'City Center',
                'Gan Nachum',
                'Kiryat Ganim',
                'Nahalat Yehuda',
                'Neve Dekalim',
                'Neve Yam',
                'Ramat Eliyahu',
                'Ramat Shikma',
                'West Rishon',
            ],
        ],
        [
            'name' => 'Petah Tikva',
            'neighborhoods' => [
                'City Center',
                'Em HaMoshavot',
                'Hadarin',
                'Kfar Ganim',
                'Kiryat Aryeh',
                'Mahane Yehuda',
                'Neve Gan',
                'Ramat Verber',
                'Yoseftal',
            ],
        ],
        [
            'name' => 'Netanya',
            'neighborhoods' => [
                'City Center',
                'Dora',
                'Ir Yamim',
                'Kiryat Hasharon',
                'Kiryat Nordau',
                'Neot Ganim',
                'North Beach',
                'Poleg',
                'Ramat Poleg',
            ],
        ],
        [
            'name' => 'Ashdod',
            'neighborhoods' => [
                'City',
                'Marina',
                'Rova Alef',
                'Rova Bet',
                'Rova Gimel',
                'Rova Dalet',
                'Rova Hey',
                'Rova Tet',
                'Rova Yud',
                'Rova Yud Alef',
                'Rova Yud Bet',
                'Rova Yud Gimel',
                'Rova Yud Zayin',
            ],
        ],
        [
            'name' => 'Ashkelon',
            'neighborhoods' => [
                'Afridar',
                'Barnea',
                'City Center',
                'Givat Zion',
                'Marina',
                'Neve Dekalim',
                'Shimshon',
            ],
        ],
        [
            'name' => 'Holon',
            'neighborhoods' => [
                'Agrobank',
                'City Center',
                'Jessy Cohen',
                'Kiryat Ben Gurion',
                'Kiryat Sharet',
                'Neot Rachel',
                'Tel Giborim',
            ],
        ],
        [
            'name' => 'Bat Yam',
            'neighborhoods' => [
                'Amidar',
                'Beachfront',
                'City Center',
                'Ramat Hanasi',
                'Ramat Yosef',
            ],
        ],
        [
            'name' => 'Ramat Gan',
            'neighborhoods' => [
                'Bursa',
                'City Center',
                'Marom Naveh',
                'Ramat Chen',
                'Ramat Efal',
                'Tel Binyamin',
            ],
        ],
        [
            'name' => 'Bnei Brak',
            'neighborhoods' => [
                'Givat Rokach',
                'Kiryat Herzog',
                'Pardes Katz',
                'Ramat Aharon',
                'Zikhron Meir',
            ],
        ],
        [
            'name' => 'Herzliya',
            'neighborhoods' => [
                'City Center',
                'Gan Rashal',
                'Herzliya Pituach',
                'Neve Amal',
                'Nof Yam',
            ],
        ],
        [
            'name' => "Ra'anana",
            'neighborhoods' => [
                'City Center',
                "East Ra'anana",
                'Kiryat Weizmann',
                'Lev HaPark',
                'Neve Zemer',
            ],
        ],
        [
            'name' => 'Kfar Saba',
            'neighborhoods' => [
                'City Center',
                'Green Neighborhood',
                'Hadassim',
                'Kaplan',
                'Yoseftal',
            ],
        ],
        [
            'name' => "Modi'in-Maccabim-Reut",
            'neighborhoods' => [
                'Avnei Chen',
                'Buchman',
                'HaKeramim',
                'Maccabim',
                'Moriah',
                'Reut',
                'Shimshoni',
            ],
        ],
        [
            'name' => 'Rehovot',
            'neighborhoods' => [
                'City Center',
                'Kfar Gvirol',
                'Kiryat Moshe',
                'Neve Amit',
                'Oshiot',
                'Science Park',
            ],
        ],
        [
            'name' => 'Lod',
            'neighborhoods' => [
                'City Center',
                'Ganei Aviv',
                'Neve Yerek',
                'Pardes Snir',
                'Ramat Eshkol',
            ],
        ],
        [
            'name' => 'Ramla',
            'neighborhoods' => [
                'City Center',
                'Ganei Dan',
                'Kiryat Menachem',
                'Neot Begin',
                'Neve David',
            ],
        ],
        [
            'name' => 'Givatayim',
            'neighborhoods' => [
                'Borochov',
                'City Center',
                'Poalei HaRakevet',
                'Rambam',
                'Shenkin',
            ],
        ],
        [
            'name' => 'Hadera',
            'neighborhoods' => [
                'Beit Eliezer',
                'City Center',
                'Givat Olga',
                'Neve Haim',
                'Park Hadera',
            ],
        ],
        [
            'name' => 'Nahariya',
            'neighborhoods' => [
                'City Center',
                'Ein Sara',
                'Galei Galil',
                'North Nahariya',
            ],
        ],
        [
            'name' => 'Acre',
            'neighborhoods' => [
                'City Center',
                'Old City',
                'Shikun Mizrah',
                'Wolfson',
            ],
        ],
        [
            'name' => 'Tiberias',
            'neighborhoods' => [
                'City Center',
                'Kiryat Shmuel',
                'Old City',
                'Ramat Kinneret',
            ],
        ],
        [
            'name' => 'Safed',
            'neighborhoods' => [
                'Artist Quarter',
                'Canaan',
                'Darom',
                'Old City',
                'Ramat Razim',
            ],
        ],
        [
            'name' => 'Eilat',
            'neighborhoods' => [
                'City Center',
                'Eilot',
                'North Beach',
                'Shahamon',
                'Tzofit',
            ],
        ],
        [
            'name' => 'Kiryat Ono',
            'neighborhoods' => [
                'City Center',
                'Kiryat Kiryati',
                'Ramat Ilan',
                'Rimon',
            ],
        ],
        [
            'name' => 'Givat Shmuel',
            'neighborhoods' => [
                'City Center',
                'Giorah',
                'Ramat Hadar',
                'Ramat Ilan',
            ],
        ],
        [
            'name' => 'Yehud-Monosson',
            'neighborhoods' => [
                'Kiryat HaSavyonim',
                'Neve Monosson',
                'Yehud',
            ],
        ],
        [
            'name' => 'Or Yehuda',
            'neighborhoods' => [
                'City Center',
                'Kiryat Giora',
                'Neve Rabin',
                'Savyonim',
            ],
        ],
        [
            'name' => 'Rosh HaAyin',
            'neighborhoods' => [
                'City Center',
                'Givat Tal',
                'Neve Afek',
                'Psagot Afek',
            ],
        ],
        [
            'name' => 'Hod HaSharon',
            'neighborhoods' => [
                'Gil Amal',
                'Had Ganim',
                'Magdiel',
                'Neve Hadar',
                'Ramatayim',
            ],
        ],
        [
            'name' => 'Ness Ziona',
            'neighborhoods' => [
                'City Center',
                'Ganei Iris',
                'Kiryat Savyonim',
                'Malibu',
            ],
        ],
        [
            'name' => 'Kiryat Gat',
            'neighborhoods' => [
                'Carmei Gat',
                'City Center',
                'Rova HaPrakhim',
                'Sderot Lakhish',
            ],
        ],
        [
            'name' => 'Kiryat Malakhi',
            'neighborhoods' => [
                'City Center',
                'Ganei Bar',
                'Kibbutz Galuyot',
            ],
        ],
        [
            'name' => 'Dimona',
            'neighborhoods' => [
                'City Center',
                'Hashlosha',
                'Neve David',
                'Peres Center',
            ],
        ],
        [
            'name' => 'Arad',
            'neighborhoods' => [
                'City Center',
                'Halamsih',
                'Rotem',
                "Ye'elim",
            ],
        ],
        [
            'name' => 'Sderot',
            'neighborhoods' => [
                'City Center',
                'Neot Aviv',
                'Neot Yitzhak Rabin',
                'Nir Am',
            ],
        ],
        [
            'name' => 'Netivot',
            'neighborhoods' => [
                'Baba Sali',
                'City Center',
                'Neve Sharon',
                'Ramat Netivot',
            ],
        ],
        [
            'name' => 'Ofakim',
            'neighborhoods' => [
                'City Center',
                'Mishor HaGefen',
                'Ramat Shaked',
                'Shapira',
            ],
        ],
        [
            'name' => 'Karmiel',
            'neighborhoods' => [
                'City Center',
                'Givat Ram',
                'Ramat Rabin',
                'Southern Karmiel',
            ],
        ],
        [
            'name' => 'Afula',
            'neighborhoods' => [
                'Afula Illit',
                'City Center',
                'Givat HaMoreh',
                'Rova Yizrael',
            ],
        ],
        [
            'name' => 'Nazareth',
            'neighborhoods' => [
                'City Center',
                'Eastern Quarter',
                'Old City',
                'Safafra',
            ],
        ],
        [
            'name' => 'Nof HaGalil',
            'neighborhoods' => [
                'City Center',
                'Dromit',
                'Har Yona',
                'Rabin',
            ],
        ],
        [
            'name' => 'Beit Shemesh',
            'neighborhoods' => [
                'City Center',
                'Givat Sharett',
                'Mishkafayim',
                'Ramat Beit Shemesh Alef',
                'Ramat Beit Shemesh Bet',
                'Ramat Beit Shemesh Gimel',
            ],
        ],
        [
            'name' => 'Maale Adumim',
            'neighborhoods' => [
                'City Center',
                'Mitzpe Nevo',
                'Nofei Sela',
                'Tzemach HaSadeh',
            ],
        ],
        [
            'name' => 'Ariel',
            'neighborhoods' => [
                'City Center',
                'Neve Shaanan',
                'Ramat HaGolan',
                'University Area',
            ],
        ],
        [
            'name' => 'Ganei Tikva',
            'neighborhoods' => [
                'City Center',
                'Ganim',
                'Givat Savyon',
                'Neve Gan',
            ],
        ],
        [
            'name' => 'Tirat Carmel',
            'neighborhoods' => [
                'City Center',
                'Galim',
                'Neot Carmel',
            ],
        ],
        ['name' => 'Ramat Hasharon', 'neighborhoods' => ['City Center', 'Neve Gan', 'Moris', 'Hadekel']],
        ['name' => 'Yavne', 'neighborhoods' => ['City Center', 'Neot Rabin', 'Green Neighborhood', 'Neve Ilan']],
        ['name' => 'Gedera', 'neighborhoods' => ['City Center', 'Givat HaTamar', 'German Colony', 'Shikun Darom']],
        ['name' => 'Beer Yaakov', 'neighborhoods' => ['City Center', 'Park Neighborhood', 'Tzameret HaMoshava']],
        ['name' => 'Migdal HaEmek', 'neighborhoods' => ['City Center', 'Ramat Eshkol', 'Yefe Nof']],
        ['name' => 'Yokneam Illit', 'neighborhoods' => ['City Center', 'Givat Yaara', 'Nof HaCarmel']],
        ['name' => 'Kiryat Bialik', 'neighborhoods' => ['City Center', 'Afek', 'Tzur Shalom']],
        ['name' => 'Kiryat Motzkin', 'neighborhoods' => ['City Center', 'Kiryat Motzkin North', 'Mishkenot Omanim']],
        ['name' => 'Kiryat Yam', 'neighborhoods' => ['City Center', 'Savyonei Yam', 'Yam Alef']],
        ['name' => 'Kiryat Ata', 'neighborhoods' => ['City Center', 'Givat Alonim', 'Kiryat Binyamin']],
        ['name' => 'Nesher', 'neighborhoods' => ['City Center', 'Givat Nesher', 'Ramot Yitzhak']],
        ['name' => 'Zikhron Yaakov', 'neighborhoods' => ['City Center', 'Givat Eden', 'Neve Habaron']],
        ['name' => 'Pardes Hanna-Karkur', 'neighborhoods' => ['Pardes Hanna', 'Karkur', 'Neve Asher']],
        ['name' => 'Kiryat Tivon', 'neighborhoods' => ['City Center', 'Kiryat Amal', 'Tivon']],
        ['name' => 'Ramat Yishai', 'neighborhoods' => ['City Center', 'Givat Ela']],
        ['name' => 'Kfar Yona', 'neighborhoods' => ['City Center', 'Sharona', 'Yafe Nof']],
        ['name' => 'Tira', 'neighborhoods' => ['City Center', 'Northern Quarter']],
        ['name' => 'Taibe', 'neighborhoods' => ['City Center', 'Eastern Quarter']],
        ['name' => 'Umm al-Fahm', 'neighborhoods' => ['City Center', 'Ein Ibrahim', 'Mualla']],
        ['name' => 'Sakhnin', 'neighborhoods' => ['City Center', 'Eastern Quarter']],
        ['name' => 'Tamra', 'neighborhoods' => ['City Center', 'Northern Quarter']],
        ['name' => 'Shefa-Amr', 'neighborhoods' => ['City Center', 'Old Quarter']],
        ['name' => 'Kiryat Shmona', 'neighborhoods' => ['City Center', 'Bimat Tel Hai', 'Yovel']],
        ['name' => 'Rosh Pina', 'neighborhoods' => ['Old Moshava', 'City Center']],
        ['name' => 'Katzrin', 'neighborhoods' => ['City Center', 'Gamla', 'Neve']],
        ['name' => 'Kiryat Arba', 'neighborhoods' => ['City Center', 'Givat HaAvot']],
        ['name' => 'Efrat', 'neighborhoods' => ['Dekel', 'Gefen', 'Tamar', 'Zayit']],
        ['name' => 'Givat ZeEv', 'neighborhoods' => ['City Center', 'Har Shmuel', 'Ramat Givat ZeEv']],
        ['name' => 'Mevaseret Zion', 'neighborhoods' => ['Mevaseret', 'Maoz Zion', 'Reches Halilim']],
        ['name' => 'Shoham', 'neighborhoods' => ['City Center', 'Tzipor', 'Hadekel']],
    ],
];
