import apiClient from '@/services/api/client'

const segment = value => encodeURIComponent(String(value))
const targetPath = (type, id) => `/social/${segment(type)}/${segment(id)}`

export const fetchNearby = (params = {}, config = {}) => apiClient.get('/nearby', { ...config, params })
export const fetchNearbyEvent = (id, config = {}) => apiClient.get(`/nearby/events/${segment(id)}`, config)
export const fetchQuestions = (params = {}, config = {}) => apiClient.get('/questions', { ...config, params })
export const fetchQuestion = (id, config = {}) => apiClient.get(`/questions/${segment(id)}`, config)
export const createQuestion = payload => apiClient.post('/questions', payload)
export const updateQuestion = (id, payload) => apiClient.patch(`/questions/${segment(id)}`, payload)
export const deleteQuestion = id => apiClient.delete(`/questions/${segment(id)}`)
export const fetchSubscriptions = (params = {}, config = {}) => apiClient.get('/subscriptions', { ...config, params })
export const fetchSubscriptionStatus = (params = {}, config = {}) => apiClient.get('/subscriptions/status', { ...config, params })
export const createSubscription = payload => apiClient.post('/subscriptions', payload)
export const updateSubscription = (id, payload) => apiClient.patch(`/subscriptions/${segment(id)}`, payload)
export const deleteSubscription = id => apiClient.delete(`/subscriptions/${segment(id)}`)
export const fetchSocialState = (type, id) => apiClient.get(targetPath(type, id))
export const fetchSocialStates = params => apiClient.get('/social-state', { params })
export const putSocialLike = (type, id) => apiClient.put(`${targetPath(type, id)}/like`)
export const deleteSocialLike = (type, id) => apiClient.delete(`${targetPath(type, id)}/like`)
export const fetchDiscussionComments = (type, id, params = {}, config = {}) => apiClient.get(`/discussions/${segment(type)}/${segment(id)}/comments`, { ...config, params })
export const createDiscussionComment = (type, id, payload) => apiClient.post(`/discussions/${segment(type)}/${segment(id)}/comments`, payload)
export const deleteDiscussionComment = id => apiClient.delete(`/comments/${segment(id)}`)
export const markQuestionHelpful = (questionId, commentId) => apiClient.put(`/questions/${segment(questionId)}/helpful/${segment(commentId)}`)
export const unmarkQuestionHelpful = (questionId, commentId) => apiClient.delete(`/questions/${segment(questionId)}/helpful/${segment(commentId)}`)
export const fetchNearbyPageOptions = (params = {}, config = {}) => apiClient.get('/nearby/page-options', { ...config, params })
export const createCommunityReport = (type, id, payload) => apiClient.post(`${targetPath(type, id)}/reports`, payload)
export const fetchCommunityReports = (params = {}, config = {}) => apiClient.get('/admin/community-reports', { ...config, params })
export const updateCommunityReport = (id, payload) => apiClient.patch(`/admin/community-reports/${segment(id)}`, payload)
