export const businessExampleInteractions = {
	en: {
		subtitle: 'Explore a filled business page with products, services, public questions, followers and guest chat. Try the preview controls below.',
		seoDescription: 'Explore a Sveevee business page example with products, services, public questions and owner replies, follow notifications, local recommendations and guest chat.',
		guestChatHint: 'Visitors can message a business without an account. Register from this chat to keep the conversation.',
		visitor: 'Guest visitor',
		guestQuestion: 'Hi! Can I pick up a gift basket this Friday?',
		businessReply: 'Hello! Yes, we can arrange a pickup time here in the chat.',
		title: 'Stay connected with local customers',
		demoLabel: 'Interactive examples',
		demoHint: 'Sample conversations. Follow and like controls only change this preview.',
		followHint: 'Signed-in visitors can follow your page and receive in-app notifications when you publish a new business ad.',
		subscriptionsHint: 'Followers manage their notifications or unfollow in My subscriptions.',
		followPreviewOn: 'Following is on in this preview.',
		followPreviewOff: 'Try Follow on the page banner above.',
		newAd: 'New business ad',
		product: 'Product',
		service: 'Service',
		questionsHint: 'Each product or service has its own detail page with public questions and owner replies. Sign in to participate.',
		productQuestion: 'Can I choose the plants and add a greeting card?',
		productReply: 'Yes. Message us with your preferred plants and the greeting you would like to include.',
		serviceQuestion: 'Does the setup include opening hours and product photos?',
		serviceReply: 'Yes. We help organize your page details and the photos you provide before publishing.',
		nearbyHint: 'In Nearby, people ask local questions, recommend businesses and like ads or replies.',
		nearbyQuestion: 'Where can I find a handmade gift nearby?',
		nearbyReply: 'Here is a local business to consider. Open its page to see the products and contact details.',
		exploreNearby: 'Explore Nearby'
	},
	he: {
		subtitle: 'גלו עמוד עסק מלא עם מוצרים, שירותים, שאלות ציבוריות, עוקבים וצ׳אט לאורחים. אפשר לנסות את כפתורי ההדגמה בהמשך.',
		seoDescription: 'גלו עמוד עסק לדוגמה ב-Sveevee עם מוצרים, שירותים, שאלות ציבוריות ותשובות בעל העסק, התראות לעוקבים, המלצות מקומיות וצ׳אט לאורחים.',
		guestChatHint: 'אפשר לשלוח הודעה לעסק ללא חשבון. הירשמו מתוך הצ׳אט כדי לשמור על השיחה.',
		visitor: 'מבקר אורח',
		guestQuestion: 'שלום! אפשר לאסוף סלסלת מתנה ביום שישי הקרוב?',
		businessReply: 'שלום! כן, אפשר לתאם כאן בצ׳אט שעת איסוף.',
		title: 'שומרים על קשר עם לקוחות בסביבה',
		demoLabel: 'דוגמאות אינטראקטיביות',
		demoHint: 'שיחות לדוגמה. כפתורי המעקב והלייק משנים רק את התצוגה המקדימה.',
		followHint: 'מבקרים מחוברים יכולים לעקוב אחר העמוד ולקבל התראות בתוך Sveevee כשמפרסמים מודעת עסק חדשה.',
		subscriptionsHint: 'העוקבים מנהלים התראות או מפסיקים לעקוב דרך ״המעקבים שלי״.',
		followPreviewOn: 'המעקב פעיל בהדגמה הזו.',
		followPreviewOff: 'נסו את כפתור המעקב בבאנר העמוד למעלה.',
		newAd: 'מודעת עסק חדשה',
		product: 'מוצר',
		service: 'שירות',
		questionsHint: 'לכל מוצר ושירות יש עמוד פרטים עם שאלות ציבוריות ותשובות של בעל העסק. יש להתחבר כדי להשתתף.',
		productQuestion: 'אפשר לבחור את הצמחים ולהוסיף כרטיס ברכה?',
		productReply: 'כן. שלחו לנו הודעה עם הצמחים המועדפים והברכה שתרצו לצרף.',
		serviceQuestion: 'הקמת העמוד כוללת שעות פתיחה ותמונות מוצרים?',
		serviceReply: 'כן. נעזור לארגן את פרטי העמוד ואת התמונות שתספקו לפני הפרסום.',
		nearbyHint: 'ב״בסביבה״ שואלים שאלות מקומיות, ממליצים על עסקים ומוסיפים לייקים למודעות או לתגובות.',
		nearbyQuestion: 'איפה אפשר למצוא מתנה בעבודת יד בסביבה?',
		nearbyReply: 'הנה עסק מקומי שכדאי לבדוק. אפשר לפתוח את העמוד כדי לראות מוצרים ופרטי קשר.',
		exploreNearby: 'גלו מה בסביבה'
	},
	ru: {
		subtitle: 'Посмотрите заполненную бизнес-страницу с товарами, услугами, публичными вопросами, подписчиками и гостевым чатом. Попробуйте кнопки в примере ниже.',
		seoDescription: 'Пример бизнес-страницы Sveevee: товары, услуги, публичные вопросы и ответы владельца, уведомления подписчикам, местные рекомендации и гостевой чат.',
		guestChatHint: 'Гости могут написать бизнесу без аккаунта. Зарегистрируйтесь из этого чата, чтобы сохранить переписку.',
		visitor: 'Гость',
		guestQuestion: 'Здравствуйте! Можно забрать подарочную корзину в эту пятницу?',
		businessReply: 'Здравствуйте! Да, время получения можно согласовать здесь, в чате.',
		title: 'Оставайтесь на связи с клиентами рядом',
		demoLabel: 'Интерактивные примеры',
		demoHint: 'Примеры переписки. Подписка и лайки меняют только этот предпросмотр.',
		followHint: 'Пользователи, вошедшие в аккаунт, могут подписаться на страницу и получать уведомления в Sveevee о новых объявлениях бизнеса.',
		subscriptionsHint: 'В разделе «Мои подписки» можно настроить уведомления или отписаться.',
		followPreviewOn: 'Подписка включена в этом примере.',
		followPreviewOff: 'Попробуйте кнопку подписки на баннере страницы выше.',
		newAd: 'Новое объявление бизнеса',
		product: 'Товар',
		service: 'Услуга',
		questionsHint: 'У каждого товара и услуги есть страница с публичными вопросами и ответами владельца. Для участия войдите в аккаунт.',
		productQuestion: 'Можно выбрать растения и добавить открытку?',
		productReply: 'Да. Напишите нам, какие растения вы предпочитаете и какой текст добавить на открытку.',
		serviceQuestion: 'В настройку входят часы работы и фотографии товаров?',
		serviceReply: 'Да. Мы поможем оформить данные страницы и предоставленные вами фотографии перед публикацией.',
		nearbyHint: 'В разделе «Рядом» задают местные вопросы, рекомендуют бизнесы и ставят лайки объявлениям или ответам.',
		nearbyQuestion: 'Где поблизости найти подарок ручной работы?',
		nearbyReply: 'Вот местный бизнес, который можно рассмотреть. На его странице есть товары и контакты.',
		exploreNearby: 'Посмотреть, что рядом'
	},
	fr: {
		subtitle: 'Explorez une page entreprise complète avec produits, services, questions publiques, abonnés et chat invité. Essayez les commandes de l’aperçu ci-dessous.',
		seoDescription: 'Découvrez une page entreprise Sveevee avec produits, services, questions publiques et réponses du propriétaire, abonnements, recommandations locales et chat invité.',
		guestChatHint: 'Les visiteurs peuvent écrire à une entreprise sans compte. Inscrivez-vous depuis ce chat pour conserver la conversation.',
		visitor: 'Visiteur invité',
		guestQuestion: 'Bonjour ! Puis-je récupérer un panier cadeau ce vendredi ?',
		businessReply: 'Bonjour ! Oui, nous pouvons convenir d’une heure de retrait ici, dans le chat.',
		title: 'Gardez le contact avec les clients du quartier',
		demoLabel: 'Exemples interactifs',
		demoHint: 'Conversations fictives. Les boutons d’abonnement et de mention J’aime modifient uniquement cet aperçu.',
		followHint: 'Les visiteurs connectés peuvent suivre votre page et recevoir une notification dans Sveevee à chaque nouvelle annonce de l’entreprise.',
		subscriptionsHint: 'Les abonnés gèrent leurs notifications ou se désabonnent dans Mes abonnements.',
		followPreviewOn: 'L’abonnement est activé dans cet aperçu.',
		followPreviewOff: 'Essayez le bouton Suivre dans la bannière ci-dessus.',
		newAd: 'Nouvelle annonce de l’entreprise',
		product: 'Produit',
		service: 'Service',
		questionsHint: 'Chaque produit ou service a sa page avec des questions publiques et les réponses du propriétaire. Connectez-vous pour participer.',
		productQuestion: 'Puis-je choisir les plantes et ajouter une carte de vœux ?',
		productReply: 'Oui. Envoyez-nous vos préférences et le message à joindre au cadeau.',
		serviceQuestion: 'La configuration comprend-elle les horaires et les photos des produits ?',
		serviceReply: 'Oui. Nous vous aidons à organiser les informations et les photos fournies avant la publication.',
		nearbyHint: 'Dans À proximité, les habitants posent des questions, recommandent des entreprises et aiment des annonces ou des réponses.',
		nearbyQuestion: 'Où trouver un cadeau artisanal dans le quartier ?',
		nearbyReply: 'Voici une entreprise locale à découvrir. Sa page présente ses produits et ses coordonnées.',
		exploreNearby: 'Découvrir À proximité'
	}
}
