const HE_CITY_LABELS = {
	Jerusalem: 'ירושלים',
	'Tel Aviv': 'תל אביב',
	Haifa: 'חיפה',
	Beersheba: 'באר שבע',
	'Rishon LeZion': 'ראשון לציון',
	'Petah Tikva': 'פתח תקווה',
	Netanya: 'נתניה',
	Ashdod: 'אשדוד',
	Ashkelon: 'אשקלון',
	Holon: 'חולון',
	'Bat Yam': 'בת ים',
	'Ramat Gan': 'רמת גן',
	'Bnei Brak': 'בני ברק',
	Herzliya: 'הרצליה',
	"Ra'anana": 'רעננה',
	'Kfar Saba': 'כפר סבא',
	"Modi'in-Maccabim-Reut": 'מודיעין-מכבים-רעות',
	Rehovot: 'רחובות',
	Lod: 'לוד',
	Ramla: 'רמלה',
	Givatayim: 'גבעתיים',
	Hadera: 'חדרה',
	Nahariya: 'נהריה',
	Acre: 'עכו',
	Tiberias: 'טבריה',
	Safed: 'צפת',
	Eilat: 'אילת',
	'Kiryat Ono': 'קריית אונו',
	'Givat Shmuel': 'גבעת שמואל',
	'Yehud-Monosson': 'יהוד-מונוסון',
	'Or Yehuda': 'אור יהודה',
	'Rosh HaAyin': 'ראש העין',
	'Hod HaSharon': 'הוד השרון',
	'Ness Ziona': 'נס ציונה',
	'Kiryat Gat': 'קריית גת',
	'Kiryat Malakhi': 'קריית מלאכי',
	Dimona: 'דימונה',
	Arad: 'ערד',
	Sderot: 'שדרות',
	Netivot: 'נתיבות',
	Ofakim: 'אופקים',
	Karmiel: 'כרמיאל',
	Afula: 'עפולה',
	Nazareth: 'נצרת',
	'Nof HaGalil': 'נוף הגליל',
	'Beit Shemesh': 'בית שמש',
	'Maale Adumim': 'מעלה אדומים',
	Ariel: 'אריאל',
	'Ganei Tikva': 'גני תקווה',
	'Tirat Carmel': 'טירת כרמל',
	'Ramat Hasharon': 'רמת השרון',
	Yavne: 'יבנה',
	Gedera: 'גדרה',
	'Beer Yaakov': 'באר יעקב',
	'Migdal HaEmek': 'מגדל העמק',
	'Yokneam Illit': 'יקנעם עילית',
	'Kiryat Bialik': 'קריית ביאליק',
	'Kiryat Motzkin': 'קריית מוצקין',
	'Kiryat Yam': 'קריית ים',
	'Kiryat Ata': 'קריית אתא',
	Nesher: 'נשר',
	'Zikhron Yaakov': 'זכרון יעקב',
	'Pardes Hanna-Karkur': 'פרדס חנה-כרכור',
	'Kiryat Tivon': 'קריית טבעון',
	'Ramat Yishai': 'רמת ישי',
	'Kfar Yona': 'כפר יונה',
	Tira: 'טירה',
	Taibe: 'טייבה',
	'Umm al-Fahm': 'אום אל-פחם',
	Sakhnin: 'סחנין',
	Tamra: 'טמרה',
	'Shefa-Amr': 'שפרעם',
	'Kiryat Shmona': 'קריית שמונה',
	'Rosh Pina': 'ראש פינה',
	Katzrin: 'קצרין',
	'Kiryat Arba': 'קריית ארבע',
	Efrat: 'אפרת',
	'Givat ZeEv': 'גבעת זאב',
	'Mevaseret Zion': 'מבשרת ציון',
	Shoham: 'שוהם'
}

const HE_NEIGHBORHOOD_LABELS = {
	'Abu Tor': 'אבו תור',
	Arnona: 'ארנונה',
	Baka: 'בקעה',
	'Bayit Vegan': 'בית וגן',
	'City Center': 'מרכז העיר',
	'Ein Karem': 'עין כרם',
	'French Hill': 'הגבעה הצרפתית',
	'German Colony': 'המושבה הגרמנית',
	Gilo: 'גילה',
	'Har Nof': 'הר נוף',
	Katamon: 'קטמון',
	'Kiryat HaYovel': 'קריית היובל',
	'Kiryat Menachem': 'קריית מנחם',
	'Kiryat Moshe': 'קריית משה',
	Musrara: 'מוסררה',
	Nachlaot: 'נחלאות',
	'Old City': 'העיר העתיקה',
	'Pisgat Zeev': 'פסגת זאב',
	Ramot: 'רמות',
	'Ramat Eshkol': 'רמת אשכול',
	Rehavia: 'רחביה',
	Sanhedria: 'סנהדריה',
	Talpiot: 'תלפיות',
	Bavli: 'בבלי',
	Florentin: 'פלורנטין',
	HaTikva: 'התקווה',
	Jaffa: 'יפו',
	'Kerem HaTeimanim': 'כרם התימנים',
	'Kiryat Shalom': 'קריית שלום',
	'Lev HaIr': 'לב העיר',
	'Neve Tzedek': 'נווה צדק',
	'Old North': 'הצפון הישן',
	'Ramat Aviv': 'רמת אביב',
	'Ramat HaHayal': 'רמת החייל',
	Rothschild: 'רוטשילד',
	Sarona: 'שרונה',
	Shapira: 'שפירא',
	'Yad Eliyahu': 'יד אליהו',
	Ahuza: 'אחוזה',
	'Bat Galim': 'בת גלים',
	'Carmel Center': 'מרכז הכרמל',
	Downtown: 'העיר התחתית',
	Hadar: 'הדר',
	'Kiryat Eliezer': 'קריית אליעזר',
	'Kiryat Haim': 'קריית חיים',
	'Kiryat Shmuel': 'קריית שמואל',
	'Neve David': 'נווה דוד',
	'Neve Shaanan': 'נווה שאנן',
	'Ramat Almogi': 'רמת אלמוגי',
	Romema: 'רוממה',
	'Stella Maris': 'סטלה מאריס',
	Vardia: 'ורדיה',
	Dalet: 'ד',
	Gimel: 'ג',
	Hey: 'ה',
	'Nahal Ashan': 'נחל עשן',
	'Nahal Beka': 'נחל בקע',
	'Neve Zeev': 'נווה זאב',
	Vav: 'ו',
	'Yud Alef': 'י״א',
	'Gan Nachum': 'גן נחום',
	'Kiryat Ganim': 'קריית גנים',
	'Nahalat Yehuda': 'נחלת יהודה',
	'Neve Dekalim': 'נווה דקלים',
	'Neve Yam': 'נווה ים',
	'Ramat Eliyahu': 'רמת אליהו',
	'Ramat Shikma': 'רמת השקמה',
	'West Rishon': 'מערב ראשון',
	'Em HaMoshavot': 'אם המושבות',
	Hadarin: 'הדרים',
	'Kfar Ganim': 'כפר גנים',
	'Kiryat Aryeh': 'קריית אריה',
	'Mahane Yehuda': 'מחנה יהודה',
	'Neve Gan': 'נווה גן',
	'Ramat Verber': 'רמת ורבר',
	Yoseftal: 'יוספטל',
	Dora: 'דורה',
	'Ir Yamim': 'עיר ימים',
	'Kiryat Hasharon': 'קריית השרון',
	'Kiryat Nordau': 'קריית נורדאו',
	'Neot Ganim': 'נאות גנים',
	'North Beach': 'חוף צפוני',
	Poleg: 'פולג',
	'Ramat Poleg': 'רמת פולג',
	City: 'העיר',
	Marina: 'מרינה',
	'Rova Alef': 'רובע א',
	'Rova Bet': 'רובע ב',
	'Rova Gimel': 'רובע ג',
	'Rova Dalet': 'רובע ד',
	'Rova Hey': 'רובע ה',
	'Rova Tet': 'רובע ט',
	'Rova Yud': 'רובע י',
	'Rova Yud Alef': 'רובע י״א',
	'Rova Yud Bet': 'רובע י״ב',
	'Rova Yud Gimel': 'רובע י״ג',
	'Rova Yud Zayin': 'רובע י״ז',
	Afridar: 'אפרידר',
	Barnea: 'ברנע',
	'Givat Zion': 'גבעת ציון',
	Shimshon: 'שמשון',
	Agrobank: 'אגרובנק',
	'Jessy Cohen': 'ג׳סי כהן',
	'Kiryat Ben Gurion': 'קריית בן גוריון',
	'Kiryat Sharet': 'קריית שרת',
	'Neot Rachel': 'נאות רחל',
	'Tel Giborim': 'תל גיבורים',
	Amidar: 'עמידר',
	Beachfront: 'קו החוף',
	'Ramat Hanasi': 'רמת הנשיא',
	'Ramat Yosef': 'רמת יוסף',
	Bursa: 'הבורסה',
	'Marom Naveh': 'מרום נווה',
	'Ramat Chen': 'רמת חן',
	'Ramat Efal': 'רמת אפעל',
	'Tel Binyamin': 'תל בנימין',
	'Givat Rokach': 'גבעת רוקח',
	'Kiryat Herzog': 'קריית הרצוג',
	'Pardes Katz': 'פרדס כץ',
	'Ramat Aharon': 'רמת אהרון',
	'Zikhron Meir': 'זכרון מאיר',
	'Gan Rashal': 'גן רש״ל',
	'Herzliya Pituach': 'הרצליה פיתוח',
	'Neve Amal': 'נווה עמל',
	'Nof Yam': 'נוף ים',
	"East Ra'anana": 'מזרח רעננה',
	'Kiryat Weizmann': 'קריית ויצמן',
	'Lev HaPark': 'לב הפארק',
	'Neve Zemer': 'נווה זמר',
	'Green Neighborhood': 'השכונה הירוקה',
	Hadassim: 'הדסים',
	Kaplan: 'קפלן',
	'Avnei Chen': 'אבני חן',
	Buchman: 'בוכמן',
	HaKeramim: 'הכרמים',
	Maccabim: 'מכבים',
	Moriah: 'מוריה',
	Reut: 'רעות',
	Shimshoni: 'שמשוני',
	'Kfar Gvirol': 'כפר גבירול',
	'Neve Amit': 'נווה עמית',
	Oshiot: 'אושיות',
	'Science Park': 'פארק המדע',
	'Ganei Aviv': 'גני אביב',
	'Neve Yerek': 'נווה ירק',
	'Pardes Snir': 'פרדס שניר',
	'Ganei Dan': 'גני דן',
	'Neot Begin': 'נאות בגין',
	Borochov: 'בורוכוב',
	'Poalei HaRakevet': 'פועלי הרכבת',
	Rambam: 'רמב״ם',
	Shenkin: 'שנקין',
	'Beit Eliezer': 'בית אליעזר',
	'Givat Olga': 'גבעת אולגה',
	'Neve Haim': 'נווה חיים',
	'Park Hadera': 'פארק חדרה',
	'Ein Sara': 'עין שרה',
	'Galei Galil': 'גלי גליל',
	'North Nahariya': 'צפון נהריה',
	'Shikun Mizrah': 'שיכון מזרח',
	Wolfson: 'וולפסון',
	'Ramat Kinneret': 'רמת כנרת',
	'Artist Quarter': 'קריית האמנים',
	Canaan: 'כנען',
	Darom: 'דרום',
	'Ramat Razim': 'רמת רזים',
	Eilot: 'אילות',
	Shahamon: 'שחמון',
	Tzofit: 'צופית',
	'Kiryat Kiryati': 'קריית קרייתי',
	'Ramat Ilan': 'רמת אילן',
	Rimon: 'רימון',
	Giorah: 'גיורא',
	'Ramat Hadar': 'רמת הדר',
	'Kiryat HaSavyonim': 'קריית הסביונים',
	'Neve Monosson': 'נווה מונוסון',
	Yehud: 'יהוד',
	'Kiryat Giora': 'קריית גיורא',
	'Neve Rabin': 'נווה רבין',
	Savyonim: 'סביונים',
	'Givat Tal': 'גבעת טל',
	'Neve Afek': 'נווה אפק',
	'Psagot Afek': 'פסגות אפק',
	'Gil Amal': 'גיל עמל',
	'Had Ganim': 'הדר גנים',
	Magdiel: 'מגדיאל',
	'Neve Hadar': 'נווה הדר',
	Ramatayim: 'רמתיים',
	'Ganei Iris': 'גני איריס',
	Malibu: 'מליבו',
	'Carmei Gat': 'כרמי גת',
	'Rova HaPrakhim': 'רובע הפרחים',
	'Sderot Lakhish': 'שדרות לכיש',
	'Ganei Bar': 'גני בר',
	'Kibbutz Galuyot': 'קיבוץ גלויות',
	Hashlosha: 'השלושה',
	'Peres Center': 'מרכז פרס',
	Halamsih: 'חלמיש',
	Rotem: 'רותם',
	"Ye'elim": 'יעלים',
	'Neot Aviv': 'נאות אביב',
	'Neot Yitzhak Rabin': 'נאות יצחק רבין',
	'Nir Am': 'ניר עם',
	'Baba Sali': 'באבא סאלי',
	'Neve Sharon': 'נווה שרון',
	'Ramat Netivot': 'רמת נתיבות',
	'Mishor HaGefen': 'מישור הגפן',
	'Ramat Shaked': 'רמת שקד',
	'Givat Ram': 'גבעת רם',
	'Ramat Rabin': 'רמת רבין',
	'Southern Karmiel': 'דרום כרמיאל',
	'Afula Illit': 'עפולה עילית',
	'Givat HaMoreh': 'גבעת המורה',
	'Rova Yizrael': 'רובע יזרעאל',
	'Eastern Quarter': 'הרובע המזרחי',
	Safafra: 'ספאפרה',
	Dromit: 'דרומית',
	'Har Yona': 'הר יונה',
	Rabin: 'רבין',
	'Givat Sharett': 'גבעת שרת',
	Mishkafayim: 'משקפיים',
	'Ramat Beit Shemesh Alef': 'רמת בית שמש א',
	'Ramat Beit Shemesh Bet': 'רמת בית שמש ב',
	'Ramat Beit Shemesh Gimel': 'רמת בית שמש ג',
	'Mitzpe Nevo': 'מצפה נבו',
	'Nofei Sela': 'נופי סלע',
	'Tzemach HaSadeh': 'צמח השדה',
	'University Area': 'אזור האוניברסיטה',
	Ganim: 'גנים',
	'Givat Savyon': 'גבעת סביון',
	Galim: 'גלים',
	'Neot Carmel': 'נאות כרמל',
	Moris: 'מוריס',
	Hadekel: 'הדקל',
	'Neot Rabin': 'נאות רבין',
	'Neve Ilan': 'נווה אילן',
	'Givat HaTamar': 'גבעת התמר',
	'Shikun Darom': 'שיכון דרום',
	'Park Neighborhood': 'שכונת הפארק',
	'Tzameret HaMoshava': 'צמרת המושבה',
	'Yefe Nof': 'יפה נוף',
	'Givat Yaara': 'גבעת יערה',
	'Nof HaCarmel': 'נוף הכרמל',
	Afek: 'אפק',
	'Tzur Shalom': 'צור שלום',
	'Kiryat Motzkin North': 'צפון קריית מוצקין',
	'Mishkenot Omanim': 'משכנות אמנים',
	'Savyonei Yam': 'סביוני ים',
	'Yam Alef': 'ים א',
	'Givat Alonim': 'גבעת אלונים',
	'Kiryat Binyamin': 'קריית בנימין',
	'Givat Nesher': 'גבעת נשר',
	'Ramot Yitzhak': 'רמות יצחק',
	'Givat Eden': 'גבעת עדן',
	'Neve Habaron': 'נווה הברון',
	'Pardes Hanna': 'פרדס חנה',
	Karkur: 'כרכור',
	'Neve Asher': 'נווה אשר',
	'Kiryat Amal': 'קריית עמל',
	Tivon: 'טבעון',
	'Givat Ela': 'גבעת אלה',
	Sharona: 'שרונה',
	'Northern Quarter': 'הרובע הצפוני',
	'Ein Ibrahim': 'עין איברהים',
	Mualla: 'מועלקה',
	'Old Quarter': 'הרובע העתיק',
	'Bimat Tel Hai': 'בימת תל חי',
	Yovel: 'יובל',
	'Old Moshava': 'המושבה הישנה',
	Gamla: 'גמלא',
	Neve: 'נווה',
	'Givat HaAvot': 'גבעת האבות',
	Dekel: 'דקל',
	Gefen: 'גפן',
	Tamar: 'תמר',
	Zayit: 'זית',
	'Har Shmuel': 'הר שמואל',
	'Ramat Givat ZeEv': 'רמת גבעת זאב',
	Mevaseret: 'מבשרת',
	'Maoz Zion': 'מעוז ציון',
	'Reches Halilim': 'רכס חלילים',
	Tzipor: 'ציפור'
}

function clean(value) {
	return String(value || '').trim()
}

export function locationLabel(value, type, locale) {
	const cleanValue = clean(value)

	if (locale !== 'he') {
		return cleanValue
	}

	const labels = type === 'city' ? HE_CITY_LABELS : HE_NEIGHBORHOOD_LABELS

	return labels[cleanValue] || cleanValue
}

export function locationOption(value, type, locale) {
	const cleanValue = clean(value)

	return {
		label: locationLabel(cleanValue, type, locale),
		value: cleanValue
	}
}

export function optionLabel(option) {
	return typeof option === 'object' && option !== null ? clean(option.label) : clean(option)
}

export function optionValue(option) {
	return typeof option === 'object' && option !== null ? clean(option.value) : clean(option)
}

export function hasOptionValue(options, value) {
	const normalizedValue = clean(value).toLocaleLowerCase()

	if (!normalizedValue) {
		return false
	}

	return options.some((option) => optionValue(option).toLocaleLowerCase() === normalizedValue)
}
