import {
	matAdd,
	matAddShoppingCart,
	matAdminPanelSettings,
	matBadge,
	matBlock,
	matCampaign,
	matChat,
	matChatBubble,
	matCheck,
	matCheckCircle,
	matClose,
	matDelete,
	matDesignServices,
	matDiversity3,
	matEdit,
	matEvent,
	matExpandMore,
	matForum,
	matHome,
	matInventory2,
	matLanguage,
	matLockReset,
	matLogin,
	matLogout,
	matMail,
	matManageAccounts,
	matMenu,
	matOpenInNew,
	matPerson,
	matPersonAdd,
	matPlace,
	matRestartAlt,
	matReviews,
	matSave,
	matSearch,
	matSend,
	matSettings,
	matShoppingCart,
	matSouth,
	matStar,
	matStorefront,
	matSupportAgent,
	matTaskAlt,
	matTune,
	matUnfoldLess,
	matUnfoldMore,
	matVerified,
	matVisibility,
	matVisibilityOff
} from '@quasar/extras/material-icons'

const materialIcons = {
	add: matAdd,
	add_shopping_cart: matAddShoppingCart,
	admin_panel_settings: matAdminPanelSettings,
	badge: matBadge,
	block: matBlock,
	campaign: matCampaign,
	chat: matChat,
	chat_bubble: matChatBubble,
	check: matCheck,
	check_circle: matCheckCircle,
	close: matClose,
	delete: matDelete,
	design_services: matDesignServices,
	diversity_3: matDiversity3,
	edit: matEdit,
	event: matEvent,
	expand_more: matExpandMore,
	forum: matForum,
	home: matHome,
	inventory_2: matInventory2,
	language: matLanguage,
	lock_reset: matLockReset,
	login: matLogin,
	logout: matLogout,
	mail: matMail,
	manage_accounts: matManageAccounts,
	menu: matMenu,
	open_in_new: matOpenInNew,
	person: matPerson,
	person_add: matPersonAdd,
	place: matPlace,
	restart_alt: matRestartAlt,
	reviews: matReviews,
	save: matSave,
	search: matSearch,
	send: matSend,
	settings: matSettings,
	shopping_cart: matShoppingCart,
	south: matSouth,
	star: matStar,
	storefront: matStorefront,
	support_agent: matSupportAgent,
	task_alt: matTaskAlt,
	tune: matTune,
	unfold_less: matUnfoldLess,
	unfold_more: matUnfoldMore,
	verified: matVerified,
	visibility: matVisibility,
	visibility_off: matVisibilityOff
}

export function materialIconMapFn(iconName) {
	const icon = materialIcons[iconName]
	return icon ? { icon } : undefined
}
