import {
	matAdd,
	matAddShoppingCart,
	matAdminPanelSettings,
	matArrowBack,
	matArrowDownward,
	matArrowUpward,
	matBadge,
	matBlock,
	matCampaign,
	matCategory,
	matChat,
	matChatBubble,
	matCheck,
	matCheckCircle,
	matClose,
	matConstruction,
	matDashboard,
	matDelete,
	matDesignServices,
	matDiversity3,
	matEdit,
	matError,
	matEvent,
	matExpandMore,
	matForum,
	matHome,
	matInfo,
	matInventory2,
	matLanguage,
	matLocalFireDepartment,
	matLockReset,
	matLogin,
	matLogout,
	matMail,
	matManageAccounts,
	matMarkEmailRead,
	matMarkEmailUnread,
	matMenu,
	matNewReleases,
	matOpenInNew,
	matPerson,
	matPersonAdd,
	matPlace,
	matRefresh,
	matRestartAlt,
	matReviews,
	matSave,
	matSchedule,
	matSearch,
	matSend,
	matSettings,
	matShoppingCart,
	matSouth,
	matStar,
	matStorefront,
	matSupportAgent,
	matTaskAlt,
	matTrendingDown,
	matTune,
	matUnfoldLess,
	matUnfoldMore,
	matVerified,
	matVerifiedUser,
	matVisibility,
	matVisibilityOff
} from '@quasar/extras/material-icons'

const materialIcons = {
	add: matAdd,
	add_shopping_cart: matAddShoppingCart,
	admin_panel_settings: matAdminPanelSettings,
	arrow_back: matArrowBack,
	arrow_downward: matArrowDownward,
	arrow_upward: matArrowUpward,
	badge: matBadge,
	block: matBlock,
	campaign: matCampaign,
	category: matCategory,
	chat: matChat,
	chat_bubble: matChatBubble,
	check: matCheck,
	check_circle: matCheckCircle,
	close: matClose,
	construction: matConstruction,
	dashboard: matDashboard,
	delete: matDelete,
	design_services: matDesignServices,
	diversity_3: matDiversity3,
	edit: matEdit,
	error: matError,
	event: matEvent,
	expand_more: matExpandMore,
	forum: matForum,
	home: matHome,
	info: matInfo,
	inventory_2: matInventory2,
	language: matLanguage,
	local_fire_department: matLocalFireDepartment,
	lock_reset: matLockReset,
	login: matLogin,
	logout: matLogout,
	mail: matMail,
	manage_accounts: matManageAccounts,
	mark_email_read: matMarkEmailRead,
	mark_email_unread: matMarkEmailUnread,
	menu: matMenu,
	new_releases: matNewReleases,
	open_in_new: matOpenInNew,
	person: matPerson,
	person_add: matPersonAdd,
	place: matPlace,
	refresh: matRefresh,
	restart_alt: matRestartAlt,
	reviews: matReviews,
	save: matSave,
	schedule: matSchedule,
	search: matSearch,
	send: matSend,
	settings: matSettings,
	shopping_cart: matShoppingCart,
	south: matSouth,
	star: matStar,
	storefront: matStorefront,
	support_agent: matSupportAgent,
	task_alt: matTaskAlt,
	trending_down: matTrendingDown,
	tune: matTune,
	unfold_less: matUnfoldLess,
	unfold_more: matUnfoldMore,
	verified: matVerified,
	verified_user: matVerifiedUser,
	visibility: matVisibility,
	visibility_off: matVisibilityOff
}

export function materialIconMapFn(iconName) {
	const icon = materialIcons[iconName]
	return icon ? { icon } : undefined
}
